### ISSUE TITLE
2017-07-07 : UAC Enhancement

### ISSUE THREAD

**Issue by BrianRuchiadi** [coder77/Kubikt-App-Bugs#21]

**Comment by weileong** [comment]
http://webpanel.kubikt.com:8887/uac/create

Tried to create new 'UAC' but nothing happened after click on Create
![image](https://user-images.githubusercontent.com/25761941/27983229-d512fa46-63e9-11e7-953e-a0e98ff42da3.png)

**Comment by BrianRuchiadi** [comment]
@weileong 
Fixed.
Please check

**Comment by weileong** [comment]
http://webpanel.kubikt.com:8887/teachers/create

![image](https://user-images.githubusercontent.com/25761941/27984028-c435606a-63fd-11e7-8046-4dff84b50c5f.png)

tried to create teacher with new maintained UAC, but no response after click on create

**Comment by BrianRuchiadi** [comment]
Done.
Please check 
@weileong

**Comment by weileong** [comment]
![image](https://user-images.githubusercontent.com/25761941/27984329-7a43a8d2-6406-11e7-9088-ba003d2e8c25.png)

Create teacher without postcode, need to add handle post code

**Comment by BrianRuchiadi** [comment]
Done.
Please pull and check.

@weileong

**Comment by weileong** [comment]
The problem still there. 

http://webpanel.kubikt.com:8887/teachers/create

Already pull latest from github.

you can try in UAT http://webpanel.kubikt.com:8887/

**Comment by BrianRuchiadi** [comment]
![image](https://user-images.githubusercontent.com/14333265/27996516-2eb75164-6516-11e7-8442-cd364b4fdf32.png)

I tested in the UAT link, and it is working
@weileong

**Comment by weileong** [comment]
@BrianRuchiadi 

It works because you did entered POSTCODE
![image](https://user-images.githubusercontent.com/25761941/28001319-2f703024-655e-11e7-8ac3-9de00a0e9be9.png)

Can you try create teacher without POSTCODE ? Since postcode is not mandatory

**Comment by BrianRuchiadi** [comment]
oo..
Okay, noted.
Sorry, i misunderstand the statement..
fixed.
And now pushed up to UAT.
Please test again
@weileong

**Comment by weileong** [comment]
@BrianRuchiadi  Thanks for your prompt action ,it works now.
